### ISSUE TITLE
ERRO na pesquisa de associados

### ISSUE THREAD

**Issue by rmfalcao** [rmfalcao/sisjuf-repositorio#12]
Ao pesquisar associados pelo campo de filtro "Nome", está sendo obtido o erro abaixo:

ERROR 2015-02-24 18:44:26,945 [BasePageBean] Erro de Generico 
java.lang.NullPointerException
	at br.org.asserjuf.sisjuf.associados.dados.AssociadoDAO.findByFilter(AssociadoDAO.java:694)
	at br.org.asserjuf.sisjuf.associados.AssociadoRN.findByFilter(AssociadoRN.java:541)
	at br.org.asserjuf.sisjuf.associados.facade.AssociadoFacade.findAssociadoByFilter(AssociadoFacade.java:39)
	at br.org.asserjuf.sisjuf.associados.cliente.AssociadoDelegate.findAssociadoByFilter(AssociadoDelegate.java:36)
	at br.org.asserjuf.sisjuf.associados.cliente.web.bean.AssociadoPageBean.consultar(AssociadoPageBean.java:539)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.apache.el.parser.AstValue.invoke(AstValue.java:131)
	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:276)
	at com.sun.faces.application.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:88)
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
	at javax.faces.component.UICommand.broadcast(UICommand.java:387)

**Comment by rmfalcao** [comment]
org.postgresql.util.PSQLException: ERROR: operator does not exist: character varying >= date
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:1548)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1316)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:191)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:452)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:351)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:255)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:92)
	at br.org.asserjuf.sisjuf.associados.dados.AssociadoDAO.findByFilter(AssociadoDAO.java:687)
	at br.org.asserjuf.sisjuf.associados.AssociadoRN.findByFilter(AssociadoRN.java:541)

**Comment by rmfalcao** [comment]
resolvido com mudança em tipo de dado no banco. erro nÃo dava antes, provavelmente foi causado por atualização da versão do PostgreSQL
